version: 0.2

phases:

  install:
    commands:
      - echo "Installing Databricks CLI"

      - curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - export PATH="$HOME/.databricks/bin:$PATH"

      - databricks version

  pre_build:
    commands:
      - echo "Configuring Databricks CLI..."

      - mkdir -p ~/.databricks

      - |
        cat > ~/.databrickscfg <<EOF
        [DEFAULT]
        host=$DATABRICKS_HOST
        token=$DATABRICKS_TOKEN
        EOF

      - echo "===== CLI VERSION ====="
      - databricks --version

      - echo "===== HOST ====="
      - echo $DATABRICKS_HOST

      - echo "===== TOKEN LENGTH ====="
      - echo ${#DATABRICKS_TOKEN}

      - echo "===== CONFIG ====="
      - cat ~/.databrickscfg

  build:
    commands:

      - echo "Creating workspace folder"
      - databricks workspace mkdirs /Workspace/Users/YOUR_EMAIL/customer-demo

      - echo "Importing Python file"
      - databricks workspace import \
          /Workspace/Users/YOUR_EMAIL/customer-demo/customer_job.py \
          --file src/customer_job.py \
          --format SOURCE \
          --language PYTHON \
          --overwrite

      - echo "Listing workspace"
      - databricks workspace list /Workspace/Users/YOUR_EMAIL/customer-demo


  post_build:
    commands:
      - echo "Build Completed"
