version: 0.2

phases:

  install:
    commands:
      - pip install databricks-cli

  pre_build:
    commands:
      - mkdir -p ~/.databricks
      - |
        cat > ~/.databrickscfg <<EOF
        [DEFAULT]
        host=$DATABRICKS_HOST
        token=$DATABRICKS_TOKEN
        EOF

      - echo "===== CLI VERSION ====="
      - databricks --version

      - echo "===== HOST ====="
      - echo $DATABRICKS_HOST

      - echo "===== TOKEN LENGTH ====="
      - echo ${#DATABRICKS_TOKEN}

      - echo "===== CONFIG ====="
      - cat ~/.databrickscfg

  build:
    commands:
      - databricks fs ls dbfs:/
